### ISSUE TITLE
New 08 Type Added in ConstAddInfo for DCUs of RAD Studio 11.3 

### ISSUE THREAD

**Issue by cnpack** [Hunter342/dcu32int#1]
RAD Studio 11.3's DCUs Add some New Information.
It seems can compile /// xxxxx   Java Doc comments in to DCU, as ConstAddInfo type 08, which is not processed in DCU32.

We suggest add below in DCU32.pas after line 2749:

      $08:  // Process 11.3 DCUs for new string such as comment after ///
        begin
          Result := ReadUIndex;
          V := ReadUIndex;
          SkipBlock(V);
        end;

**Comment by Hunter342** [comment]
Updated
